package ru.abrikosov.cleanrate.ui

import ru.abrikosov.cleanrate.data.RateOrigin
import ru.abrikosov.cleanrate.data.RateSource
import ru.abrikosov.cleanrate.data.UiLanguage
import ru.abrikosov.cleanrate.data.ChartPeriod

sealed interface UiMessage {
    data object SourcesUnavailable : UiMessage
    data object RatesUpdated : UiMessage
    data object AddBankRate : UiMessage
    data object KeepOneCurrency : UiMessage
    data class ManualRateDeleted(val code: String) : UiMessage
    data class ManualRateSaved(val code: String) : UiMessage
}

class UiText(val language: UiLanguage) {
    private fun tr(russian: String, english: String, french: String): String = when (language) {
        UiLanguage.RUSSIAN -> russian
        UiLanguage.ENGLISH -> english
        UiLanguage.FRENCH -> french
    }

    val appName = tr("Чистый курс", "Clean Rate", "Taux clair")
    val tagline = tr(
        "Без рекламы и регистрации",
        "No ads or registration",
        "Sans publicité ni inscription",
    )
    val refreshRates = tr("Обновить курсы", "Refresh rates", "Actualiser les taux")
    val manageCurrencies = tr("Настроить валюты", "Manage currencies", "Gérer les devises")
    val settings = tr("Настройки", "Settings", "Réglages")
    val settingsIntro = tr(
        "Отклик клавиш, конфиденциальность и валюты на главном экране",
        "Key feedback, privacy, and currencies on the main screen",
        "Retour des touches, confidentialité et devises de l’écran principal",
    )
    val privacyPolicy = tr("Конфиденциальность", "Privacy", "Confidentialité")
    val privacySummary = tr(
        "Приложение не собирает, не хранит и не передаёт персональные данные. Рекламы, аналитики и регистрации нет.",
        "The app does not collect, store, or share personal data. It has no ads, analytics, or registration.",
        "L’application ne collecte, ne stocke et ne partage aucune donnée personnelle. Elle ne contient ni publicité, ni analyse, ni inscription.",
    )
    val privacyNetwork = tr(
        "По защищённому соединению загружаются только общедоступные текущие и исторические курсы. Введённые суммы в сеть не отправляются. Сервер технически видит IP-адрес запроса, но приложение его не сохраняет и не использует для идентификации.",
        "Only public current and historical rates are downloaded over secure connections. Entered amounts are never sent over the network. The server technically sees the request IP address, but the app does not store or use it for identification.",
        "Seuls les taux publics actuels et historiques sont téléchargés via des connexions sécurisées. Les montants saisis ne sont jamais envoyés sur le réseau. Le serveur voit techniquement l’adresse IP de la requête, mais l’application ne la stocke pas et ne l’utilise pas pour vous identifier.",
    )
    val privacyStorage = tr(
        "Настройки и кэш курсов хранятся только на устройстве и удаляются вместе с приложением.",
        "Settings and cached rates stay on the device and are removed when the app is uninstalled.",
        "Les réglages et les taux mis en cache restent sur l’appareil et sont supprimés lors de la désinstallation.",
    )
    val privacyPermissions = tr(
        "Разрешения используются только для доступа к интернету и включённой пользователем вибрации клавиш.",
        "Permissions are used only for internet access and user-enabled key vibration.",
        "Les autorisations servent uniquement à l’accès Internet et à la vibration des touches activée par l’utilisateur.",
    )
    val close = tr("Закрыть", "Close", "Fermer")
    val keypadFeedback = tr("Отклик клавиш", "Key feedback", "Retour des touches")
    val keySound = tr("Звук клавиш", "Key sound", "Son des touches")
    val keySoundDescription = tr(
        "Мультимедийный звук; громкость — кнопками телефона",
        "Media sound; adjust it with the phone’s volume buttons",
        "Son multimédia ; réglez-le avec les boutons de volume",
    )
    val keyVibration = tr("Вибрация клавиш", "Key vibration", "Vibration des touches")
    val keyVibrationDescription = tr(
        "Отдельный короткий импульс приложения",
        "A short vibration generated by the app",
        "Une courte vibration produite par l’application",
    )
    val changeLanguage = tr("Изменить язык", "Change language", "Changer de langue")
    val savedMarketRate = tr("Встроенный резервный курс", "Built-in fallback rates", "Taux de secours intégrés")
    val outdatedRate = tr(
        "Сохранённый курс устарел",
        "Saved rates are out of date",
        "Les taux enregistrés ne sont plus à jour",
    )
    val refreshRequired = tr(
        "Нужно подключение для получения актуального курса",
        "Connect to the internet to get current rates",
        "Connectez-vous à Internet pour obtenir les taux actuels",
    )
    val bankRatesNotSet = tr(
        "Курсы банка ещё не заданы",
        "Bank rates are not set yet",
        "Les taux de la banque ne sont pas encore définis",
    )
    val marketReference = tr(
        "Ежедневный справочный курс",
        "Daily reference rate",
        "Taux indicatif quotidien",
    )
    val unpublishedUseMarket = tr(
        "Неопубликованные валюты — мировой резерв",
        "Unlisted currencies use global rates",
        "Devises non publiées : taux mondiaux",
    )
    val remainingUseMarket = tr(
        "Остальные валюты — мировой резерв",
        "Other currencies use global rates",
        "Autres devises : taux mondiaux",
    )
    val chooseRateSource = tr(
        "Выбрать источник курса",
        "Select rate source",
        "Choisir la source des taux",
    )
    val deleteCharacter = tr("Удалить символ", "Delete character", "Supprimer le caractère")
    val changeSign = tr("Изменить знак", "Change sign", "Changer le signe")
    val equals = tr("Равно", "Equals", "Égal")
    val hideKeyboard = tr("Скрыть клавиатуру", "Hide keypad", "Masquer le clavier")
    val showKeyboard = tr("Показать клавиатуру", "Show keypad", "Afficher le clavier")
    val charts = tr("График", "Chart", "Graphique")
    val chartTitle = tr("Динамика курса", "Rate history", "Historique du taux")
    val back = tr("Назад", "Back", "Retour")
    val swapCurrencies = tr("Поменять валюты местами", "Swap currencies", "Inverser les devises")
    val selectBaseCurrency = tr("Выбрать исходную валюту", "Select base currency", "Choisir la devise de départ")
    val selectQuoteCurrency = tr("Выбрать валюту результата", "Select quote currency", "Choisir la devise d’arrivée")
    val amountForChart = tr("Сумма", "Amount", "Montant")
    val latestValue = tr("Последнее значение", "Latest value", "Dernière valeur")
    val chartTouchHint = tr(
        "Коснитесь или проведите по графику, чтобы выбрать дату",
        "Tap or drag across the chart to choose a date",
        "Touchez ou faites glisser sur le graphique pour choisir une date",
    )
    val selectChartPoint = tr("Выбрать дату на графике", "Select a chart date", "Choisir une date sur le graphique")
    val previousChartPoint = tr("Предыдущая дата", "Previous date", "Date précédente")
    val nextChartPoint = tr("Следующая дата", "Next date", "Date suivante")
    val showLatestValue = tr("К последнему", "Latest", "Dernier taux")
    val minimum = tr("Мин", "Min", "Min")
    val maximum = tr("Макс", "Max", "Max")
    val loadingHistory = tr(
        "Загружаю историю курса…",
        "Loading rate history…",
        "Chargement de l’historique…",
    )
    val historyUnavailable = tr(
        "История пока недоступна. Проверьте интернет и попробуйте ещё раз.",
        "Rate history is unavailable. Check your connection and try again.",
        "L’historique est indisponible. Vérifiez votre connexion et réessayez.",
    )
    val retry = tr("Повторить", "Try again", "Réessayer")
    val savedHistory = tr(
        "Показана сохранённая история",
        "Showing saved history",
        "Historique enregistré affiché",
    )
    fun incompleteHistory(missingCount: Int) = tr(
        "Нет данных для дат: $missingCount; интервалы показаны по календарю",
        "Missing dates: $missingCount; spacing follows the calendar",
        "Dates manquantes : $missingCount ; l’espacement suit le calendrier",
    )
    val historySource = tr(
        "Исторические данные · currency-api",
        "Historical data · currency-api",
        "Données historiques · currency-api",
    )
    val historyDisclaimer = tr(
        "Справочная мировая динамика; курс банка может отличаться.",
        "Indicative global history; your bank’s rate may differ.",
        "Historique mondial indicatif ; le taux de votre banque peut différer.",
    )
    val chooseCurrency = tr("Выберите валюту", "Choose a currency", "Choisissez une devise")
    val sourcePickerTitle = tr("Источник курса", "Rate source", "Source des taux")
    val sourcePickerIntro = tr(
        "Источник можно менять в любой момент — суммы пересчитаются сразу.",
        "Change the source at any time — amounts update immediately.",
        "Changez la source à tout moment : les montants sont recalculés immédiatement.",
    )
    val marketSourceDescription = tr(
        "Открытый ежедневный справочный курс; без регистрации и API-ключа.",
        "Open daily reference rates with no registration or API key.",
        "Taux indicatifs quotidiens ouverts, sans inscription ni clé API.",
    )
    val cbrSourceDescription = tr(
        "Официальные курсы Банка России к рублю; для остальных валют — мировой резерв.",
        "Official Bank of Russia rates against the ruble; global rates for other currencies.",
        "Taux officiels de la Banque de Russie par rapport au rouble ; taux mondiaux pour les autres devises.",
    )
    val addRatesWithPencil = tr(
        "Введите курсы своего банка через карандаш около валюты.",
        "Enter your bank rates using the pencil next to a currency.",
        "Saisissez les taux de votre banque avec le crayon placé près d’une devise.",
    )
    val cbrDisclaimer = tr(
        "Официальный курс ЦБ РФ справочный и не обязывает банки покупать или продавать валюту по нему.",
        "The official Bank of Russia rate is indicative and does not require banks to trade at that rate.",
        "Le taux officiel de la Banque de Russie est indicatif et n’oblige pas les banques à l’appliquer.",
    )
    val cbrData = tr("Данные ЦБ РФ", "Bank of Russia data", "Données de la Banque de Russie")
    val marketData = tr("Открытый источник", "Open source", "Source ouverte")
    val selected = tr("Выбрано", "Selected", "Sélectionné")
    val currenciesOnScreen = tr("Валюты на экране", "Currencies on screen", "Devises affichées")
    val currencyManagerIntro = tr(
        "Добавляйте, меняйте порядок и задавайте свой курс",
        "Add, reorder, and set your own rates",
        "Ajoutez, réorganisez et définissez vos propres taux",
    )
    val currencySearch = tr("Код или название валюты", "Currency code or name", "Code ou nom de la devise")
    val onMainScreen = tr("На главном экране", "On the main screen", "Sur l’écran principal")
    val allCurrencies = tr("Все валюты", "All currencies", "Toutes les devises")
    val manualRateInUse = tr("Используется свой курс", "Custom rate in use", "Taux personnalisé utilisé")
    val enterPositiveNumber = tr(
        "Введите положительное число",
        "Enter a positive number",
        "Saisissez un nombre positif",
    )
    val save = tr("Сохранить", "Save", "Enregistrer")
    val reset = tr("Сбросить", "Reset", "Réinitialiser")
    val cancel = tr("Отмена", "Cancel", "Annuler")
    val languagePickerTitle = tr("Язык интерфейса", "Interface language", "Langue de l’interface")
    val languagePickerIntro = tr(
        "Выбор сохранится на этом устройстве.",
        "Your choice will be saved on this device.",
        "Votre choix sera enregistré sur cet appareil.",
    )

    fun rateFor(date: String) = tr("Курс от $date", "Rate from $date", "Taux du $date")

    fun checked(date: String) = tr("Проверено $date", "Checked $date", "Vérifié le $date")

    fun valueFor(date: String) = tr("На $date", "As of $date", "Au $date")

    fun cbrRateFor(date: String) = tr(
        "Курс ЦБ РФ на $date",
        "Bank of Russia rate for $date",
        "Taux de la Banque de Russie au $date",
    )

    fun ownRateCount(count: Int) = tr(
        "Своих курсов: $count",
        "Custom rates: $count",
        "Taux personnalisés : $count",
    )

    fun customSourceDescription(count: Int) = tr(
        "Задано своих курсов: $count; для остальных — мировой резерв.",
        "$count custom rates; global rates for the other currencies.",
        "$count taux personnalisés ; taux mondiaux pour les autres devises.",
    )

    fun sourceName(source: RateSource, compact: Boolean = false): String = when (source) {
        RateSource.MARKET -> tr("Мировой", "Global", "Mondial")
        RateSource.CBR -> if (compact) tr("ЦБ РФ", "BoR", "BdR") else tr(
            "ЦБ РФ",
            "Bank of Russia",
            "Banque de Russie",
        )
        RateSource.CUSTOM -> tr("Мой банк", "My bank", "Ma banque")
    }

    fun originName(origin: RateOrigin): String = when (origin) {
        RateOrigin.MARKET -> tr("Мир", "World", "Monde")
        RateOrigin.CBR -> tr("ЦБ", "BoR", "BdR")
        RateOrigin.CUSTOM -> tr("Мой", "Mine", "Moi")
    }

    fun moveUp(code: String) = tr("Поднять $code", "Move $code up", "Monter $code")
    fun moveDown(code: String) = tr("Опустить $code", "Move $code down", "Descendre $code")
    fun editRate(code: String) = tr("Изменить курс $code", "Edit $code rate", "Modifier le taux $code")
    fun removeCurrency(code: String) = tr("Убрать $code", "Remove $code", "Retirer $code")
    fun addCurrency(code: String) = tr("Добавить $code", "Add $code", "Ajouter $code")
    fun manualRateTitle(code: String) = tr(
        "Курс моего банка · $code",
        "My bank rate · $code",
        "Taux de ma banque · $code",
    )

    fun manualRatePrompt(code: String) = tr(
        "Введите, сколько $code ваш банк даёт за один доллар США.",
        "Enter how many $code your bank gives for one US dollar.",
        "Indiquez combien de $code votre banque donne pour un dollar américain.",
    )

    fun referenceRate(value: String) = tr(
        "Справочный курс: $value",
        "Reference rate: $value",
        "Taux indicatif : $value",
    )

    fun languageName(language: UiLanguage): String = when (language) {
        UiLanguage.RUSSIAN -> "Русский"
        UiLanguage.ENGLISH -> "English"
        UiLanguage.FRENCH -> "Français"
    }

    fun chartPeriod(period: ChartPeriod): String = when (period) {
        ChartPeriod.WEEK -> tr("7д", "7d", "7j")
        ChartPeriod.MONTH -> tr("1м", "1m", "1m")
        ChartPeriod.THREE_MONTHS -> tr("3м", "3m", "3m")
        ChartPeriod.SIX_MONTHS -> tr("6м", "6m", "6m")
        ChartPeriod.YEAR -> tr("1г", "1y", "1a")
    }

    fun chartSummary(baseCode: String, quoteCode: String, pointCount: Int): String = tr(
        "График $baseCode к $quoteCode, точек: $pointCount",
        "$baseCode to $quoteCode chart, $pointCount points",
        "Graphique $baseCode vers $quoteCode, $pointCount points",
    )

    fun selectedChartPoint(baseCode: String, quoteCode: String, date: String, rate: String): String = tr(
        "Выбрано $date: 1 $baseCode равен $rate $quoteCode",
        "Selected $date: 1 $baseCode equals $rate $quoteCode",
        "Date sélectionnée $date : 1 $baseCode vaut $rate $quoteCode",
    )

    fun message(message: UiMessage): String = when (message) {
        UiMessage.SourcesUnavailable -> tr(
            "Часть источников недоступна — используются сохранённые курсы",
            "Some sources are unavailable — saved rates are being used",
            "Certaines sources sont indisponibles : les taux enregistrés sont utilisés",
        )
        UiMessage.RatesUpdated -> tr("Курсы проверены", "Rates checked", "Taux vérifiés")
        UiMessage.AddBankRate -> addRatesWithPencil
        UiMessage.KeepOneCurrency -> tr(
            "На экране должна остаться хотя бы одна валюта",
            "Keep at least one currency on the screen",
            "Conservez au moins une devise à l’écran",
        )
        is UiMessage.ManualRateDeleted -> tr(
            "Свой курс ${message.code} удалён",
            "Custom ${message.code} rate removed",
            "Le taux personnalisé ${message.code} a été supprimé",
        )
        is UiMessage.ManualRateSaved -> tr(
            "Курс банка для ${message.code} сохранён и включён",
            "Bank rate for ${message.code} saved and enabled",
            "Le taux bancaire ${message.code} a été enregistré et activé",
        )
    }
}
